# <img align='right' width='300' height='150' src='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-pBrNZGBG-sevpbicgO9LsnAKS0BkEFUWmw&s'>
## <font color='seablue'>**Benchmarking Large Language Models**</font>
### <font color='black'>**Assessing Process Mining Tasks with RAG**</font>
#### <font color='grey'> *João Caldeira @ 2024*</font>
This Notebook runs multiple benchmarks on process mining tasks with different LLMs.
<hr>

In [52]:
#!/opt/homebrew/bin/python3 -m pip install ollama --break-system-packages
#!pip install ollama
#!pip install pandas
#!pip install openpyxl
#!pip install jinja2 
#!pip install csv
#!pip install requests

In [53]:
from Benchmark import Benchmark

In [54]:
#bm = Benchmark( settings_file="ul-projects-settings.xlsx" )
bm = Benchmark( settings_file="ims-process-settings.xlsx" )

In [55]:
bm.settings

,ENABLED,ENGINE,URL,MODELS,VISUAL_MODELS,OPTIONS,QUESTIONS_PATH,ANSWERS_PATH,JUDGING,JUDGING_URL,JUDGING_MODELS,JUDGING_PATH,JUDGING_OPTIONS,OBS,API_KEY,JUDGING_API_KEY
4,T,Ollama,http://localhost:11434,"qwen3,llama3.2","llava,gpt-4o,gpt-4-turbo,gpt-4-vision",4096,projects_questions,projects_answers,ChatGPT,https://api.openai.com/v1/chat/completions,gpt-4.1,projects_judging,4096,"llama3.1,llama3.2,gemma2,qwen2.5,phi3.5,mistral,llava",YOUR_OPENAI_API_KEY_HERE,YOUR_OPENAI_API_KEY_HERE
7,T,ChatGPT,http://localhost:11434,"gpt-4o,gpt-3.5-turbo","llava,gpt-4o,gpt-4-turbo,gpt-4-vision",4096,projects_questions,projects_answers,ChatGPT,https://api.openai.com/v1/chat/completions,gpt-4.1,projects_judging,4096,"llama3.1,llama3.2,gemma2,qwen2.5,phi3.5,mistral,llava",YOUR_OPENAI_API_KEY_HERE,YOUR_OPENAI_API_KEY_HERE
8,T,Ollama,http://localhost:11434,deepseek-r1,"llava,gpt-4o,gpt-4-turbo,gpt-4-vision",4096,projects_questions,projects_answers,ChatGPT,https://api.openai.com/v1/chat/completions,gpt-4.1,projects_judging,4096,"llama3.1,llama3.2,gemma2,qwen2.5,phi3.5,mistral,llava",YOUR_OPENAI_API_KEY_HERE,YOUR_OPENAI_API_KEY_HERE

In [56]:
#bm.settings
bm.runBenchmarks(questioning=False, judging=True) 
#judge the previous answers

Running ChatGPT Model gpt-4.1 in 00:01
['gpt-4.1', 'qwen3', 'US285851', 'Q28.txt']
Running ChatGPT Model gpt-4.1 in 00:03
['gpt-4.1', 'qwen3', 'US285851', 'Q29.txt']
Running ChatGPT Model gpt-4.1 in 00:01
['gpt-4.1', 'qwen3', 'US285851', 'Q30.txt']
Running ChatGPT Model gpt-4.1 in 00:01
['gpt-4.1', 'qwen3', 'US285851', 'Q31.txt']
Running ChatGPT Model gpt-4.1 in 00:03
['gpt-4.1', 'qwen3', 'US285851', 'Q32.txt']
Running ChatGPT Model gpt-4.1 in 00:03
['gpt-4.1', 'qwen3', 'US285851', 'Q33.txt']
Running ChatGPT Model gpt-4.1 in 00:02
['gpt-4.1', 'qwen3', 'US285851', 'Q34.txt']
Running ChatGPT Model gpt-4.1 in 00:01
['gpt-4.1', 'qwen3', 'US285851', 'Q35.txt']
Running ChatGPT Model gpt-4.1 in 00:02
['gpt-4.1', 'qwen3', 'US285851', 'Q36.txt']
Running ChatGPT Model gpt-4.1 in 00:03
['gpt-4.1', 'qwen3', 'US285851', 'Q37.txt']
Running ChatGPT Model gpt-4.1 in 00:01
['gpt-4.1', 'qwen3', 'US293949', 'Q38.txt']
Running ChatGPT Model gpt-4.1 in 00:03
['gpt-4.1', 'qwen3', 'US293949', 'Q39.txt']
Running ChatGPT Model gpt-4.1 in 00:02
['gpt-4.1', 'qwen3', 'US293949', 'Q40.txt']
Running ChatGPT Model gpt-4.1 in 00:01
['gpt-4.1', 'qwen3', 'US293949', 'Q41.txt']
Running ChatGPT Model gpt-4.1 in 00:02
['gpt-4.1', 'qwen3', 'US293949', 'Q42.txt']
Running ChatGPT Model gpt-4.1 in 00:03
['gpt-4.1', 'qwen3', 'US293949', 'Q43.txt']
Running ChatGPT Model gpt-4.1 in 00:02
['gpt-4.1', 'qwen3', 'US293949', 'Q44.txt']
Running ChatGPT Model gpt-4.1 in 00:02
['gpt-4.1', 'qwen3', 'US293949', 'Q45.txt']
Running ChatGPT Model gpt-4.1 in 00:01
['gpt-4.1', 'qwen3', 'US293949', 'Q46.txt']
Running ChatGPT Model gpt-4.1 in 00:01
['gpt-4.1', 'qwen3', 'US293949', 'Q47.txt']
Running ChatGPT Model gpt-4.1 in 00:01
['gpt-4.1', 'qwen3', 'US37581', '285851', '293949', 'Q48.txt']
Running ChatGPT Model gpt-4.1 in 00:04
['gpt-4.1', 'qwen3', 'US37581', '285851', '293949', 'Q49.txt']
Running ChatGPT Model gpt-4.1 in 00:02
['gpt-4.1', 'qwen3', 'US37581', '285851', '293949', 'Q50.txt']
Running ChatGPT Model gpt-4.1 in 00:02
['gpt-4.1', 'qwen3', 'US37581', '285851', '293949', 'Q51.txt']
Running ChatGPT Model gpt-4.1 in 00:01
['gpt-4.1', 'qwen3', 'US37581', '285851', '293949', 'Q52.txt']
Running ChatGPT Model gpt-4.1 in 00:02
['gpt-4.1', 'qwen3', 'US37581', '285851', '293949', 'Q53.txt']
Running ChatGPT Model gpt-4.1 in 00:01
['gpt-4.1', 'qwen3', 'US37581', '285851', '293949', 'Q54.txt']
Running ChatGPT Model gpt-4.1 in 00:02
['gpt-4.1', 'qwen3', 'US37581', '285851', '293949', 'Q55.txt']
Running ChatGPT Model gpt-4.1 in 00:02
['gpt-4.1', 'qwen3', 'US37581', '285851', '293949', 'Q56.txt']
Running ChatGPT Model gpt-4.1 in 00:03
['gpt-4.1', 'qwen3', 'US37581', '285851', '293949', 'Q57.txt']
Running ChatGPT Model gpt-4.1 in 00:01
['gpt-4.1', 'qwen3', 'US37581', 'Q18.txt']
Running ChatGPT Model gpt-4.1 in 00:02
['gpt-4.1', 'qwen3', 'US37581', 'Q19.txt']
Running ChatGPT Model gpt-4.1 in 00:01
['gpt-4.1', 'qwen3', 'US37581', 'Q20.txt']
Running ChatGPT Model gpt-4.1 in 00:01
['gpt-4.1', 'qwen3', 'US37581', 'Q21.txt']
Running ChatGPT Model gpt-4.1 in 00:02
['gpt-4.1', 'qwen3', 'US37581', 'Q22.txt']
Running ChatGPT Model gpt-4.1 in 00:01
['gpt-4.1', 'qwen3', 'US37581', 'Q23.txt']
Running ChatGPT Model gpt-4.1 in 00:04
['gpt-4.1', 'qwen3', 'US37581', 'Q24.txt']
Running ChatGPT Model gpt-4.1 in 00:02
['gpt-4.1', 'qwen3', 'US37581', 'Q25.txt']
Running ChatGPT Model gpt-4.1 in 00:02
['gpt-4.1', 'qwen3', 'US37581', 'Q26.txt']
Running ChatGPT Model gpt-4.1 in 00:02
['gpt-4.1', 'qwen3', 'US37581', 'Q27.txt']
Running ChatGPT Model gpt-4.1 in 00:02
['gpt-4.1', 'llama3.2', 'US285851', 'Q28.txt']
Running ChatGPT Model gpt-4.1 in 00:04
['gpt-4.1', 'llama3.2', 'US285851', 'Q29.txt']
Running ChatGPT Model gpt-4.1 in 00:02
['gpt-4.1', 'llama3.2', 'US285851', 'Q30.txt']
Running ChatGPT Model gpt-4.1 in 00:02
['gpt-4.1', 'llama3.2', 'US285851', 'Q31.txt']
Running ChatGPT Model gpt-4.1 in 00:03
['gpt-4.1', 'llama3.2', 'US285851', 'Q32.txt']
Running ChatGPT Model gpt-4.1 in 00:02
['gpt-4.1', 'llama3.2', 'US285851', 'Q33.txt']
Running ChatGPT Model gpt-4.1 in 00:01
['gpt-4.1', 'llama3.2', 'US285851', 'Q34.txt']
Running ChatGPT Model gpt-4.1 in 00:02
['gpt-4.1', 'llama3.2', 'US285851', 'Q35.txt']
Running ChatGPT Model gpt-4.1 in 00:03
['gpt-4.1', 'llama3.2', 'US285851', 'Q36.txt']
Running ChatGPT Model gpt-4.1 in 00:01
['gpt-4.1', 'llama3.2', 'US285851', 'Q37.txt']
Running ChatGPT Model gpt-4.1 in 00:02
['gpt-4.1', 'llama3.2', 'US293949', 'Q38.txt']
Running ChatGPT Model gpt-4.1 in 00:03
['gpt-4.1', 'llama3.2', 'US293949', 'Q39.txt']
Running ChatGPT Model gpt-4.1 in 00:02
['gpt-4.1', 'llama3.2', 'US293949', 'Q40.txt']
Running ChatGPT Model gpt-4.1 in 00:06
['gpt-4.1', 'llama3.2', 'US293949', 'Q41.txt']
Running ChatGPT Model gpt-4.1 in 00:02
['gpt-4.1', 'llama3.2', 'US293949', 'Q42.txt']
Running ChatGPT Model gpt-4.1 in 00:02
['gpt-4.1', 'llama3.2', 'US293949', 'Q43.txt']
Running ChatGPT Model gpt-4.1 in 00:01
['gpt-4.1', 'llama3.2', 'US293949', 'Q44.txt']
Running ChatGPT Model gpt-4.1 in 00:03
['gpt-4.1', 'llama3.2', 'US293949', 'Q45.txt']
Running ChatGPT Model gpt-4.1 in 00:02
['gpt-4.1', 'llama3.2', 'US293949', 'Q46.txt']
Running ChatGPT Model gpt-4.1 in 00:03
['gpt-4.1', 'llama3.2', 'US293949', 'Q47.txt']
Running ChatGPT Model gpt-4.1 in 00:01
['gpt-4.1', 'llama3.2', 'US37581', '285851', '293949', 'Q48.txt']
Running ChatGPT Model gpt-4.1 in 00:04
['gpt-4.1', 'llama3.2', 'US37581', '285851', '293949', 'Q49.txt']
Running ChatGPT Model gpt-4.1 in 00:02
['gpt-4.1', 'llama3.2', 'US37581', '285851', '293949', 'Q50.txt']
Running ChatGPT Model gpt-4.1 in 00:02
['gpt-4.1', 'llama3.2', 'US37581', '285851', '293949', 'Q51.txt']
Running ChatGPT Model gpt-4.1 in 00:06
['gpt-4.1', 'llama3.2', 'US37581', '285851', '293949', 'Q52.txt']
Running ChatGPT Model gpt-4.1 in 00:05
['gpt-4.1', 'llama3.2', 'US37581', '285851', '293949', 'Q53.txt']
Running ChatGPT Model gpt-4.1 in 00:02
['gpt-4.1', 'llama3.2', 'US37581', '285851', '293949', 'Q54.txt']
Running ChatGPT Model gpt-4.1 in 00:04
['gpt-4.1', 'llama3.2', 'US37581', '285851', '293949', 'Q55.txt']
Running ChatGPT Model gpt-4.1 in 00:03
['gpt-4.1', 'llama3.2', 'US37581', '285851', '293949', 'Q56.txt']
Running ChatGPT Model gpt-4.1 in 00:07
['gpt-4.1', 'llama3.2', 'US37581', '285851', '293949', 'Q57.txt']
Running ChatGPT Model gpt-4.1 in 00:03
['gpt-4.1', 'llama3.2', 'US37581', 'Q18.txt']
Running ChatGPT Model gpt-4.1 in 00:03
['gpt-4.1', 'llama3.2', 'US37581', 'Q19.txt']
Running ChatGPT Model gpt-4.1 in 00:01
['gpt-4.1', 'llama3.2', 'US37581', 'Q20.txt']
Running ChatGPT Model gpt-4.1 in 00:02
['gpt-4.1', 'llama3.2', 'US37581', 'Q21.txt']
Running ChatGPT Model gpt-4.1 in 00:02
['gpt-4.1', 'llama3.2', 'US37581', 'Q22.txt']
Running ChatGPT Model gpt-4.1 in 00:02
['gpt-4.1', 'llama3.2', 'US37581', 'Q23.txt']
Running ChatGPT Model gpt-4.1 in 00:04
['gpt-4.1', 'llama3.2', 'US37581', 'Q24.txt']
Running ChatGPT Model gpt-4.1 in 00:03
['gpt-4.1', 'llama3.2', 'US37581', 'Q25.txt']
Running ChatGPT Model gpt-4.1 in 00:03
['gpt-4.1', 'llama3.2', 'US37581', 'Q26.txt']
Running ChatGPT Model gpt-4.1 in 00:02
['gpt-4.1', 'llama3.2', 'US37581', 'Q27.txt']
Running ChatGPT Model gpt-4.1 in 00:02
['gpt-4.1', 'gpt-4o', 'US285851', 'Q28.txt']
Running ChatGPT Model gpt-4.1 in 00:02
['gpt-4.1', 'gpt-4o', 'US285851', 'Q29.txt']
Running ChatGPT Model gpt-4.1 in 00:02
['gpt-4.1', 'gpt-4o', 'US285851', 'Q30.txt']
Running ChatGPT Model gpt-4.1 in 00:02
['gpt-4.1', 'gpt-4o', 'US285851', 'Q31.txt']
Running ChatGPT Model gpt-4.1 in 00:02
['gpt-4.1', 'gpt-4o', 'US285851', 'Q32.txt']
Running ChatGPT Model gpt-4.1 in 00:02
['gpt-4.1', 'gpt-4o', 'US285851', 'Q33.txt']
Running ChatGPT Model gpt-4.1 in 00:02
['gpt-4.1', 'gpt-4o', 'US285851', 'Q34.txt']
Running ChatGPT Model gpt-4.1 in 00:02
['gpt-4.1', 'gpt-4o', 'US285851', 'Q35.txt']
Running ChatGPT Model gpt-4.1 in 00:01
['gpt-4.1', 'gpt-4o', 'US285851', 'Q36.txt']
Running ChatGPT Model gpt-4.1 in 00:01
['gpt-4.1', 'gpt-4o', 'US285851', 'Q37.txt']
Running ChatGPT Model gpt-4.1 in 00:03
['gpt-4.1', 'gpt-4o', 'US293949', 'Q38.txt']
Running ChatGPT Model gpt-4.1 in 00:01
['gpt-4.1', 'gpt-4o', 'US293949', 'Q39.txt']
Running ChatGPT Model gpt-4.1 in 00:03
['gpt-4.1', 'gpt-4o', 'US293949', 'Q40.txt']
Running ChatGPT Model gpt-4.1 in 00:04
['gpt-4.1', 'gpt-4o', 'US293949', 'Q41.txt']
Running ChatGPT Model gpt-4.1 in 00:03
['gpt-4.1', 'gpt-4o', 'US293949', 'Q42.txt']
Running ChatGPT Model gpt-4.1 in 00:02
['gpt-4.1', 'gpt-4o', 'US293949', 'Q43.txt']
Running ChatGPT Model gpt-4.1 in 00:02
['gpt-4.1', 'gpt-4o', 'US293949', 'Q44.txt']
Running ChatGPT Model gpt-4.1 in 00:01
['gpt-4.1', 'gpt-4o', 'US293949', 'Q45.txt']
Running ChatGPT Model gpt-4.1 in 00:04
['gpt-4.1', 'gpt-4o', 'US293949', 'Q46.txt']
Running ChatGPT Model gpt-4.1 in 00:01
['gpt-4.1', 'gpt-4o', 'US293949', 'Q47.txt']
Running ChatGPT Model gpt-4.1 in 00:05
['gpt-4.1', 'gpt-4o', 'US37581', '285851', '293949', 'Q48.txt']
Running ChatGPT Model gpt-4.1 in 00:04
['gpt-4.1', 'gpt-4o', 'US37581', '285851', '293949', 'Q49.txt']
Running ChatGPT Model gpt-4.1 in 00:02
['gpt-4.1', 'gpt-4o', 'US37581', '285851', '293949', 'Q50.txt']
Running ChatGPT Model gpt-4.1 in 00:03
['gpt-4.1', 'gpt-4o', 'US37581', '285851', '293949', 'Q51.txt']
Running ChatGPT Model gpt-4.1 in 00:03
['gpt-4.1', 'gpt-4o', 'US37581', '285851', '293949', 'Q52.txt']
Running ChatGPT Model gpt-4.1 in 00:02
['gpt-4.1', 'gpt-4o', 'US37581', '285851', '293949', 'Q53.txt']
Running ChatGPT Model gpt-4.1 in 00:03
['gpt-4.1', 'gpt-4o', 'US37581', '285851', '293949', 'Q54.txt']
Running ChatGPT Model gpt-4.1 in 00:02
['gpt-4.1', 'gpt-4o', 'US37581', '285851', '293949', 'Q55.txt']
Running ChatGPT Model gpt-4.1 in 00:03
['gpt-4.1', 'gpt-4o', 'US37581', '285851', '293949', 'Q56.txt']
Running ChatGPT Model gpt-4.1 in 00:03
['gpt-4.1', 'gpt-4o', 'US37581', '285851', '293949', 'Q57.txt']
Running ChatGPT Model gpt-4.1 in 00:02
['gpt-4.1', 'gpt-4o', 'US37581', 'Q18.txt']
Running ChatGPT Model gpt-4.1 in 00:02
['gpt-4.1', 'gpt-4o', 'US37581', 'Q19.txt']
Running ChatGPT Model gpt-4.1 in 00:01
['gpt-4.1', 'gpt-4o', 'US37581', 'Q20.txt']
Running ChatGPT Model gpt-4.1 in 00:02
['gpt-4.1', 'gpt-4o', 'US37581', 'Q21.txt']
Running ChatGPT Model gpt-4.1 in 00:02
['gpt-4.1', 'gpt-4o', 'US37581', 'Q22.txt']
Running ChatGPT Model gpt-4.1 in 00:02
['gpt-4.1', 'gpt-4o', 'US37581', 'Q23.txt']
Running ChatGPT Model gpt-4.1 in 00:01
['gpt-4.1', 'gpt-4o', 'US37581', 'Q24.txt']
Running ChatGPT Model gpt-4.1 in 00:01
['gpt-4.1', 'gpt-4o', 'US37581', 'Q25.txt']
Running ChatGPT Model gpt-4.1 in 00:01
['gpt-4.1', 'gpt-4o', 'US37581', 'Q26.txt']
Running ChatGPT Model gpt-4.1 in 00:01
['gpt-4.1', 'gpt-4o', 'US37581', 'Q27.txt']
Running ChatGPT Model gpt-4.1 in 00:02
['gpt-4.1', 'gpt-3.5-turbo', 'US285851', 'Q28.txt']
Running ChatGPT Model gpt-4.1 in 00:03
['gpt-4.1', 'gpt-3.5-turbo', 'US285851', 'Q29.txt']
Running ChatGPT Model gpt-4.1 in 00:03
['gpt-4.1', 'gpt-3.5-turbo', 'US285851', 'Q30.txt']
Running ChatGPT Model gpt-4.1 in 00:03
['gpt-4.1', 'gpt-3.5-turbo', 'US285851', 'Q31.txt']
Running ChatGPT Model gpt-4.1 in 00:05
['gpt-4.1', 'gpt-3.5-turbo', 'US285851', 'Q32.txt']
Running ChatGPT Model gpt-4.1 in 00:02
['gpt-4.1', 'gpt-3.5-turbo', 'US285851', 'Q33.txt']
Running ChatGPT Model gpt-4.1 in 00:03
['gpt-4.1', 'gpt-3.5-turbo', 'US285851', 'Q34.txt']
Running ChatGPT Model gpt-4.1 in 00:04
['gpt-4.1', 'gpt-3.5-turbo', 'US285851', 'Q35.txt']
Running ChatGPT Model gpt-4.1 in 00:03
['gpt-4.1', 'gpt-3.5-turbo', 'US285851', 'Q36.txt']
Running ChatGPT Model gpt-4.1 in 00:02
['gpt-4.1', 'gpt-3.5-turbo', 'US285851', 'Q37.txt']
Running ChatGPT Model gpt-4.1 in 00:01
['gpt-4.1', 'gpt-3.5-turbo', 'US293949', 'Q38.txt']
Running ChatGPT Model gpt-4.1 in 00:03
['gpt-4.1', 'gpt-3.5-turbo', 'US293949', 'Q39.txt']
Running ChatGPT Model gpt-4.1 in 00:02
['gpt-4.1', 'gpt-3.5-turbo', 'US293949', 'Q40.txt']
Running ChatGPT Model gpt-4.1 in 00:02
['gpt-4.1', 'gpt-3.5-turbo', 'US293949', 'Q41.txt']
Running ChatGPT Model gpt-4.1 in 00:02
['gpt-4.1', 'gpt-3.5-turbo', 'US293949', 'Q42.txt']
Running ChatGPT Model gpt-4.1 in 00:02
['gpt-4.1', 'gpt-3.5-turbo', 'US293949', 'Q43.txt']
Running ChatGPT Model gpt-4.1 in 00:01
['gpt-4.1', 'gpt-3.5-turbo', 'US293949', 'Q44.txt']
Running ChatGPT Model gpt-4.1 in 00:02
['gpt-4.1', 'gpt-3.5-turbo', 'US293949', 'Q45.txt']
Running ChatGPT Model gpt-4.1 in 00:03
['gpt-4.1', 'gpt-3.5-turbo', 'US293949', 'Q46.txt']
Running ChatGPT Model gpt-4.1 in 00:02
['gpt-4.1', 'gpt-3.5-turbo', 'US293949', 'Q47.txt']
Running ChatGPT Model gpt-4.1 in 00:02
['gpt-4.1', 'gpt-3.5-turbo', 'US37581', '285851', '293949', 'Q48.txt']
Running ChatGPT Model gpt-4.1 in 00:02
['gpt-4.1', 'gpt-3.5-turbo', 'US37581', '285851', '293949', 'Q49.txt']
Running ChatGPT Model gpt-4.1 in 00:04
['gpt-4.1', 'gpt-3.5-turbo', 'US37581', '285851', '293949', 'Q50.txt']
Running ChatGPT Model gpt-4.1 in 00:04
['gpt-4.1', 'gpt-3.5-turbo', 'US37581', '285851', '293949', 'Q51.txt']
Running ChatGPT Model gpt-4.1 in 00:02
['gpt-4.1', 'gpt-3.5-turbo', 'US37581', '285851', '293949', 'Q52.txt']
Running ChatGPT Model gpt-4.1 in 00:02
['gpt-4.1', 'gpt-3.5-turbo', 'US37581', '285851', '293949', 'Q53.txt']
Running ChatGPT Model gpt-4.1 in 00:02
['gpt-4.1', 'gpt-3.5-turbo', 'US37581', '285851', '293949', 'Q54.txt']
Running ChatGPT Model gpt-4.1 in 00:01
['gpt-4.1', 'gpt-3.5-turbo', 'US37581', '285851', '293949', 'Q55.txt']
Running ChatGPT Model gpt-4.1 in 00:01
['gpt-4.1', 'gpt-3.5-turbo', 'US37581', '285851', '293949', 'Q56.txt']
Running ChatGPT Model gpt-4.1 in 00:01
['gpt-4.1', 'gpt-3.5-turbo', 'US37581', '285851', '293949', 'Q57.txt']
Running ChatGPT Model gpt-4.1 in 00:02
['gpt-4.1', 'gpt-3.5-turbo', 'US37581', 'Q18.txt']
Running ChatGPT Model gpt-4.1 in 00:03
['gpt-4.1', 'gpt-3.5-turbo', 'US37581', 'Q19.txt']
Running ChatGPT Model gpt-4.1 in 00:03
['gpt-4.1', 'gpt-3.5-turbo', 'US37581', 'Q20.txt']
Running ChatGPT Model gpt-4.1 in 00:01
['gpt-4.1', 'gpt-3.5-turbo', 'US37581', 'Q21.txt']
Running ChatGPT Model gpt-4.1 in 00:01
['gpt-4.1', 'gpt-3.5-turbo', 'US37581', 'Q22.txt']
Running ChatGPT Model gpt-4.1 in 00:02
['gpt-4.1', 'gpt-3.5-turbo', 'US37581', 'Q23.txt']
Running ChatGPT Model gpt-4.1 in 00:04
['gpt-4.1', 'gpt-3.5-turbo', 'US37581', 'Q24.txt']
Running ChatGPT Model gpt-4.1 in 00:02
['gpt-4.1', 'gpt-3.5-turbo', 'US37581', 'Q25.txt']
Running ChatGPT Model gpt-4.1 in 00:02
['gpt-4.1', 'gpt-3.5-turbo', 'US37581', 'Q26.txt']
Running ChatGPT Model gpt-4.1 in 00:02
['gpt-4.1', 'gpt-3.5-turbo', 'US37581', 'Q27.txt']
Running ChatGPT Model gpt-4.1 in 00:01
['gpt-4.1', 'deepseek-r1', 'US285851', 'Q28.txt']
Running ChatGPT Model gpt-4.1 in 00:04
['gpt-4.1', 'deepseek-r1', 'US285851', 'Q29.txt']
Running ChatGPT Model gpt-4.1 in 00:01
['gpt-4.1', 'deepseek-r1', 'US285851', 'Q30.txt']
Running ChatGPT Model gpt-4.1 in 00:03
['gpt-4.1', 'deepseek-r1', 'US285851', 'Q31.txt']
Running ChatGPT Model gpt-4.1 in 00:02
['gpt-4.1', 'deepseek-r1', 'US285851', 'Q32.txt']
Running ChatGPT Model gpt-4.1 in 00:02
['gpt-4.1', 'deepseek-r1', 'US285851', 'Q33.txt']
Running ChatGPT Model gpt-4.1 in 00:02
['gpt-4.1', 'deepseek-r1', 'US285851', 'Q34.txt']
Running ChatGPT Model gpt-4.1 in 00:03
['gpt-4.1', 'deepseek-r1', 'US285851', 'Q35.txt']
Running ChatGPT Model gpt-4.1 in 00:03
['gpt-4.1', 'deepseek-r1', 'US285851', 'Q36.txt']
Running ChatGPT Model gpt-4.1 in 00:01
['gpt-4.1', 'deepseek-r1', 'US285851', 'Q37.txt']
Running ChatGPT Model gpt-4.1 in 00:01
['gpt-4.1', 'deepseek-r1', 'US293949', 'Q38.txt']
Running ChatGPT Model gpt-4.1 in 00:02
['gpt-4.1', 'deepseek-r1', 'US293949', 'Q39.txt']
Running ChatGPT Model gpt-4.1 in 00:02
['gpt-4.1', 'deepseek-r1', 'US293949', 'Q40.txt']
Running ChatGPT Model gpt-4.1 in 00:02
['gpt-4.1', 'deepseek-r1', 'US293949', 'Q41.txt']
Running ChatGPT Model gpt-4.1 in 00:02
['gpt-4.1', 'deepseek-r1', 'US293949', 'Q42.txt']
Running ChatGPT Model gpt-4.1 in 00:02
['gpt-4.1', 'deepseek-r1', 'US293949', 'Q43.txt']
Running ChatGPT Model gpt-4.1 in 00:01
['gpt-4.1', 'deepseek-r1', 'US293949', 'Q44.txt']
Running ChatGPT Model gpt-4.1 in 00:02
['gpt-4.1', 'deepseek-r1', 'US293949', 'Q45.txt']
Running ChatGPT Model gpt-4.1 in 00:04
['gpt-4.1', 'deepseek-r1', 'US293949', 'Q46.txt']
Running ChatGPT Model gpt-4.1 in 00:02
['gpt-4.1', 'deepseek-r1', 'US293949', 'Q47.txt']
Running ChatGPT Model gpt-4.1 in 00:01
['gpt-4.1', 'deepseek-r1', 'US37581', '285851', '293949', 'Q48.txt']
Running ChatGPT Model gpt-4.1 in 00:05
['gpt-4.1', 'deepseek-r1', 'US37581', '285851', '293949', 'Q49.txt']
Running ChatGPT Model gpt-4.1 in 00:01
['gpt-4.1', 'deepseek-r1', 'US37581', '285851', '293949', 'Q50.txt']
Running ChatGPT Model gpt-4.1 in 00:04
['gpt-4.1', 'deepseek-r1', 'US37581', '285851', '293949', 'Q51.txt']
Running ChatGPT Model gpt-4.1 in 00:04
['gpt-4.1', 'deepseek-r1', 'US37581', '285851', '293949', 'Q52.txt']
Running ChatGPT Model gpt-4.1 in 00:03
['gpt-4.1', 'deepseek-r1', 'US37581', '285851', '293949', 'Q53.txt']
Running ChatGPT Model gpt-4.1 in 00:03
['gpt-4.1', 'deepseek-r1', 'US37581', '285851', '293949', 'Q54.txt']
Running ChatGPT Model gpt-4.1 in 00:03
['gpt-4.1', 'deepseek-r1', 'US37581', '285851', '293949', 'Q55.txt']
Running ChatGPT Model gpt-4.1 in 00:04
['gpt-4.1', 'deepseek-r1', 'US37581', '285851', '293949', 'Q56.txt']
Running ChatGPT Model gpt-4.1 in 00:01
['gpt-4.1', 'deepseek-r1', 'US37581', '285851', '293949', 'Q57.txt']
Running ChatGPT Model gpt-4.1 in 00:01
['gpt-4.1', 'deepseek-r1', 'US37581', 'Q18.txt']
Running ChatGPT Model gpt-4.1 in 00:03
['gpt-4.1', 'deepseek-r1', 'US37581', 'Q19.txt']
Running ChatGPT Model gpt-4.1 in 00:01
['gpt-4.1', 'deepseek-r1', 'US37581', 'Q20.txt']
Running ChatGPT Model gpt-4.1 in 00:02
['gpt-4.1', 'deepseek-r1', 'US37581', 'Q21.txt']
Running ChatGPT Model gpt-4.1 in 00:02
['gpt-4.1', 'deepseek-r1', 'US37581', 'Q22.txt']
Running ChatGPT Model gpt-4.1 in 00:01
['gpt-4.1', 'deepseek-r1', 'US37581', 'Q23.txt']
Running ChatGPT Model gpt-4.1 in 00:02
['gpt-4.1', 'deepseek-r1', 'US37581', 'Q24.txt']
Running ChatGPT Model gpt-4.1 in 00:01
['gpt-4.1', 'deepseek-r1', 'US37581', 'Q25.txt']
Running ChatGPT Model gpt-4.1 in 00:02
['gpt-4.1', 'deepseek-r1', 'US37581', 'Q26.txt']
Running ChatGPT Model gpt-4.1 in 00:01
['gpt-4.1', 'deepseek-r1', 'US37581', 'Q27.txt']

In [57]:
bm.output

,Engine,Model Name,Judging Name,Judging Model,Judging Path,Judging Grade
0,Ollama,qwen3,ChatGPT,gpt-4.1,projects_judging/Ollama/ChatGPT\gpt-4.1_qwen3_US285851_Q28.txt,3.000
1,Ollama,qwen3,ChatGPT,gpt-4.1,projects_judging/Ollama/ChatGPT\gpt-4.1_qwen3_US285851_Q29.txt,2.000
2,Ollama,qwen3,ChatGPT,gpt-4.1,projects_judging/Ollama/ChatGPT\gpt-4.1_qwen3_US285851_Q30.txt,3.000
3,Ollama,qwen3,ChatGPT,gpt-4.1,projects_judging/Ollama/ChatGPT\gpt-4.1_qwen3_US285851_Q31.txt,3.000
4,Ollama,qwen3,ChatGPT,gpt-4.1,projects_judging/Ollama/ChatGPT\gpt-4.1_qwen3_US285851_Q32.txt,3.000
...,...,...,...,...,...,...
195,Ollama,deepseek-r1,ChatGPT,gpt-4.1,projects_judging/Ollama/ChatGPT\gpt-4.1_deepseek-r1_US37581_Q23.txt,3.000
196,Ollama,deepseek-r1,ChatGPT,gpt-4.1,projects_judging/Ollama/ChatGPT\gpt-4.1_deepseek-r1_US37581_Q24.txt,1.000
197,Ollama,deepseek-r1,ChatGPT,gpt-4.1,projects_judging/Ollama/ChatGPT\gpt-4.1_deepseek-r1_US37581_Q25.txt,3.000
198,Ollama,deepseek-r1,ChatGPT,gpt-4.1,projects_judging/Ollama/ChatGPT\gpt-4.1_deepseek-r1_US37581_Q26.txt,3.000
199,Ollama,deepseek-r1,ChatGPT,gpt-4.1,projects_judging/Ollama/ChatGPT\gpt-4.1_deepseek-r1_US37581_Q27.txt,3.000

In [58]:

bm.output_to_latex( "benchmark_output.tex", caption="My Caption", label="tbl:lr-results" )